### ISSUE TITLE
QtCreator can't see this template

### ISSUE THREAD

**Issue by R3D9477** [aleixq/qtcreator-makeEspArduino-template#1]
@aleixq  Hi. My QtCreator 4.9.0 can't see this template (category Other Project doesn't contain ESP8266) :(
(I'm on Linux Mint 17 x64)

I cloned this repo to templates forlder (as described in [doc.qt](https://doc.qt.io/qtcreator/creator-project-wizards.html#locating-wizards)).

What I'm doing wrong?

**Comment by R3D9477** [comment]
@aleixq Ok, seems like there is a little [mistake](https://github.com/aleixq/qtcreator-makeEspArduino-template/blob/master/esp8266/wizard.json#L146) in wizard.json ;-)
(and this file have a several strange duplicated parameters)

**Comment by aleixq** [comment]
Hi r3d9u11, patches are welcome :)

**Comment by R3D9477** [comment]
@aleixq I did a little PR :)
